spring:
  h2:
    console:
      enabled: true
      path: /h2/
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  sql:
    init:
      mode: always
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none

#================================
# Pretty-print JSON responses
#================================
jackson:
  default-property-inclusion: non_null
  serialization:
    indent_output: true